p8105_hw2_wy2486
================

## Problem 1

**Read and clean the data**

    ## # A tibble: 1,868 × 32
    ##    division line   station_name station_latitude station_longitude route1 route2
    ##    <chr>    <chr>  <chr>                   <dbl>             <dbl> <chr>  <chr> 
    ##  1 BMT      4 Ave… 25th St                  40.7             -74.0 R      <NA>  
    ##  2 BMT      4 Ave… 25th St                  40.7             -74.0 R      <NA>  
    ##  3 BMT      4 Ave… 36th St                  40.7             -74.0 N      R     
    ##  4 BMT      4 Ave… 36th St                  40.7             -74.0 N      R     
    ##  5 BMT      4 Ave… 36th St                  40.7             -74.0 N      R     
    ##  6 BMT      4 Ave… 45th St                  40.6             -74.0 R      <NA>  
    ##  7 BMT      4 Ave… 45th St                  40.6             -74.0 R      <NA>  
    ##  8 BMT      4 Ave… 45th St                  40.6             -74.0 R      <NA>  
    ##  9 BMT      4 Ave… 45th St                  40.6             -74.0 R      <NA>  
    ## 10 BMT      4 Ave… 53rd St                  40.6             -74.0 R      <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 25 more variables: route3 <chr>, route4 <chr>, route5 <chr>, route6 <chr>,
    ## #   route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>,
    ## #   entrance_type <chr>, entry <chr>, exit_only <chr>, vending <chr>,
    ## #   staffing <chr>, staff_hours <chr>, ada <lgl>, ada_notes <chr>,
    ## #   free_crossover <lgl>, north_south_street <chr>, east_west_street <chr>,
    ## #   corner <chr>, entrance_latitude <dbl>, entrance_longitude <dbl>, …

**Retain line, station, name, station latitude / longitude, routes
served, entry, vending, entrance type, and ADA compliance**

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

    ## # A tibble: 1,868 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

The original dataset `nycsubway_df` contains 32 variables and 1,868
rows.The dataset was cleaned by: 1. Changing the variable names so that
it is all in lowercase and with underscore (\_), for example from
Station Longitude to station_longitude. 2. All “.”, ” “, or”NA” are all
treated as NA. 3. Then, only some of the variables were retained dataset
using the code `select`. 4. Also, the code `mutate` and `case_match`
were used to change *entry* to logical variable (TRUE or FALSE).

After these steps, the cleaned dataset `nycsubwaymutate_df` contains 19
variables and 1,868 rows. The 19 variables include *Line, Station Name,
Station Latitude, Station Longitude, Routes(1-11), Entry, Vending*, and
*ADA Compliance*. This dataset is not tidy because there are many of the
routes 1-11, it would be better to change it to just one column (route).

**How many distinct stations are there? Note that stations are
identified both by name and by line (e.g. 125th St 8th Avenue; 125st
Broadway; 125st Lenox); the distinct function may be useful here.**

    ## [1] 465

**How many stations are ADA compliant?**

    ## [1] 84

What proportion of station entrances / exits without vending allow
entrance?

    ## [1] 0.3770492

**Reformat data so that route number and route name are distinct
variables.**
<!-- I use ChatGPT here to debug my code, as there is error message saying that there are some of the route datasets that are not all the same type of data, so needed to be changed to character, hence, I use the mutate(across(route1:route11, as.character) -->

| line | station_name | station_latitude | station_longitude | entry | vending | entrance_type | ada | route_number | route_name |
|:---|:---|---:|---:|:---|:---|:---|:---|:---|:---|
| 4 Avenue | 25th St | 40.6604 | -73.99809 | TRUE | YES | Stair | FALSE | route1 | R |
| 4 Avenue | 25th St | 40.6604 | -73.99809 | TRUE | YES | Stair | FALSE | route2 | NA |
| 4 Avenue | 25th St | 40.6604 | -73.99809 | TRUE | YES | Stair | FALSE | route3 | NA |
| 4 Avenue | 25th St | 40.6604 | -73.99809 | TRUE | YES | Stair | FALSE | route4 | NA |
| 4 Avenue | 25th St | 40.6604 | -73.99809 | TRUE | YES | Stair | FALSE | route5 | NA |
| 4 Avenue | 25th St | 40.6604 | -73.99809 | TRUE | YES | Stair | FALSE | route6 | NA |
| 4 Avenue | 25th St | 40.6604 | -73.99809 | TRUE | YES | Stair | FALSE | route7 | NA |
| 4 Avenue | 25th St | 40.6604 | -73.99809 | TRUE | YES | Stair | FALSE | route8 | NA |
| 4 Avenue | 25th St | 40.6604 | -73.99809 | TRUE | YES | Stair | FALSE | route9 | NA |
| 4 Avenue | 25th St | 40.6604 | -73.99809 | TRUE | YES | Stair | FALSE | route10 | NA |

**How many distinct stations serve the A train?**

    ## [1] 60

**Of the stations that serve the A train, how many are ADA compliant?**

    ## [1] 17

## Problem 2

**Read and clean the data**

``` r
mr_trash_wheel_df =
  read_excel(
    "./datahw2/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N742",
    na = c("", "NA", ".")
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    plastic_bottles = as.numeric(plastic_bottles),
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )

prof_trash_wheel_df =
  read_excel(
    "./datahw2/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M139",
    na = c("", "NA", ".")
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    plastic_bottles = as.numeric(plastic_bottles),
    trash_wheel = "Professor Trash Wheel"
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `plastic_bottles = as.numeric(plastic_bottles)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

``` r
gwynnda_df =
  read_excel(
    "./datahw2/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:L394",
    na = c("", "NA", ".")
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    plastic_bottles = as.numeric(plastic_bottles),
    trash_wheel = "Gwynnda"
  )
```

``` r
alltrashwheel_df =
  bind_rows(
    mr_trash_wheel_df,
    prof_trash_wheel_df,
    gwynnda_df
  )
alltrashwheel_df
```

    ## # A tibble: 1,269 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,259 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

There are 1269 observations and 15 variables. The key variables are
dumpster, month, year, date, weight (tons), volume cubic (yards),
plastic bottles, polystyrene, cigarette butts, glass bottles, plastic
bags, wrappers, sports balls, homes_powered, and trash wheel.

The total weight of trash collected by Professor Trash Wheel is 294.96
tons.

The total number of cigarette butts collected by Gwynnda in June of 2022
is 1.812^{4}.
